# permissions for end users to edit indextemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: indextemplate-editor-role
rules:
- apiGroups:
  - elasticsearch.elasticrest.io
  resources:
  - indextemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearch.elasticrest.io
  resources:
  - indextemplates/status
  verbs:
  - get
