# permissions for end users to view indextemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: indextemplate-viewer-role
rules:
- apiGroups:
  - elasticsearch.elasticrest.io
  resources:
  - indextemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticsearch.elasticrest.io
  resources:
  - indextemplates/status
  verbs:
  - get
