---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debian
  name: interactive-deployment
  namespace: elasticrest-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
      - args:
        - "while true; do sleep 9999999 ; done"
        image: debian
        command: ["/bin/sh", "-c"]
        imagePullPolicy: IfNotPresent
        name: debian
      serviceAccountName: elasticrest-operator-controller-manager
